version: "3.7"
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/mypms
            - ./.docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - php
        networks:
            - default

    docs:
        image: nginx:latest
        ports:
            - 8081:80
        volumes:
            - ./docs:/usr/share/nginx/html
        networks:
            - default

    php:
        build: ./.docker/php/
        volumes:
            - ./:/var/www/mypms
            - ./.docker/php/conf.d:/usr/local/etc/php/custom.d
        environment:
            PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"

    db:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: CRM
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - persistent:/var/lib/mysql
        networks:
          - default

    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080
        environment:
            ADMINER_DEFAULT_SERVER: db
            ADMINER_DEFAULT_DB_NAME: myDb

    postfix:
        image: juanluisbaptiste/postfix:latest
        ports:
            - 25
        environment:
            SMTP_SERVER: smtp.mailtrap.io
            SMTP_USERNAME: 633c658fd5f4db
            SMTP_PASSWORD: 0bea9aeaa336c9
            SERVER_HOSTNAME: mailtrap.io

    redis:
        build: ./.docker/redis/
        ports:
            - 6379:6379
        volumes:
            - ./.docker/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
volumes:
    persistent:
